create table if not exists products (title varchar(255),cost double, primary key (title))
insert into products values ('banana' , 1.2)
insert into products values ('apple' , 2.3)
insert into products values ('milk' , 2.3)
insert into products values ('cheese' , 3.4)
insert into products values ('soya milk' , 4.5)
insert into products values ('bread' , 5.6)
insert into products values ('egg' , 6.7)
insert into products values ('rice' , 7.8)
insert into products values ('pesto' , 8.9)
insert into products values ('avocado' , 9.1)
insert into products values ('pasta' , 10.2)
insert into products values ('pizza' , 11.3)
insert into products values ('tomato' , 12.4)
insert into products values ('mushroom' , 13.5)
insert into products values ('coffee' , 14.6)
insert into products values ('tea' , 15.7)
insert into products values ('sugar' , 16.8)
insert into products values ('salt' , 17.9)
insert into products values ('chocolate' , 18.1)
insert into products values ('cake' , 19.2)

create table if not exists cart (product_name varchar(255),quantity int, primary key (product_name))
/*insert into cart values ('test1',5)

create table if not exists customers (id integer,name varchar(255), primary key (id))
insert into customers values (1, 'liza')
insert into customers values (2, 'daniel')
create table if not exists customers_products (customer_id integer,product_id integer)
insert into customers_products values (1,1)
insert into customers_products values (1,2)
insert into customers_products values (2,2)
insert into customers_products values (2,3)
 */
