create table if not exists products (id integer,title varchar(255),cost double, primary key (id))
insert into products values (1, 'banana' , 1.2)
insert into products values (2, 'apple' , 2.3)
insert into products values (3, 'milk' , 2.3)
insert into products values (4, 'cheese' , 3.4)
insert into products values (5, 'soya milk' , 4.5)
insert into products values (6, 'bread' , 5.6)
insert into products values (7, 'egg' , 6.7)
insert into products values (8, 'rice' , 7.8)
insert into products values (9, 'pesto' , 8.9)
insert into products values (10, 'avocado' , 9.1)
insert into products values (11, 'pasta' , 10.2)
insert into products values (12, 'pizza' , 11.3)
insert into products values (13, 'tomato' , 12.4)
insert into products values (14, 'mushroom' , 13.5)
insert into products values (15, 'coffee' , 14.6)
insert into products values (16, 'tea' , 15.7)
insert into products values (17, 'sugar' , 16.8)
insert into products values (18, 'salt' , 17.9)
insert into products values (19, 'chocolate' , 18.1)
insert into products values (20, 'cake' , 19.2)
create table if not exists customers (id integer,name varchar(255), primary key (id))
insert into customers values (1, 'liza')
insert into customers values (2, 'daniel')
create table if not exists customers_products (customer_id integer,product_id integer)
insert into customers_products values (1,1)
insert into customers_products values (1,2)
insert into customers_products values (2,2)
insert into customers_products values (2,3)
