create table if not exists products (title varchar(255),cost double, primary key (title))

    insert into products values ('banana' , 1.2)
    insert into products values ('apple' , 2.3)
    insert into products values ('milk' , 2.3)
    insert into products values ('cheese' , 3.4)
    insert into products values ('soya milk' , 4.5)
    insert into products values ('bread' , 5.6)
    insert into products values ('egg' , 6.7)
    insert into products values ('rice' , 7.8)
    insert into products values ('pesto' , 8.9)
    insert into products values ('avocado' , 9.1)
    insert into products values ('pasta' , 10.2)
    insert into products values ('pizza' , 11.3)
    insert into products values ('tomato' , 12.4)
    insert into products values ('mushroom' , 13.5)
    insert into products values ('coffee' , 14.6)
    insert into products values ('tea' , 15.7)
    insert into products values ('sugar' , 16.8)
    insert into products values ('salt' , 17.9)
    insert into products values ('chocolate' , 18.1)
    insert into products values ('cake' , 19.2)