create table if not exists products (title varchar(255),cost double, primary key (title))

create table if not exists users (user_name varchar(255), password varchar(255),name varchar(255), surname varchar(255),adress varchar(255), phone_number varchar(255), email varchar(255), primary key (user_name))
create table if not exists user_role (user_name varchar(255), roles varchar(255),primary key (user_name,roles))

create table if not exists cart (product_name varchar(255),quantity int, user_name varchar(255),primary key (product_name))

create table if not exists orders (order_id  bigserial not null,user_name varchar(255),delivery_address varchar(255),status varchar(255),date varchar(255),primary key(order_id))

create table if not exists order_product (title varchar(255),order_id bigserial not null,primary key(order_id,title))

    insert into products values ('banana' , 1.2)
    insert into products values ('apple' , 2.3)
    insert into products values ('milk' , 2.3)
    insert into products values ('cheese' , 3.4)
    insert into products values ('soya milk' , 4.5)
    insert into products values ('bread' , 5.6)
    insert into products values ('egg' , 6.7)
    insert into products values ('rice' , 7.8)
    insert into products values ('pesto' , 8.9)
    insert into products values ('avocado' , 9.1)
    insert into products values ('pasta' , 10.2)
    insert into products values ('pizza' , 11.3)
    insert into products values ('tomato' , 12.4)
    insert into products values ('mushroom' , 13.5)
    insert into products values ('coffee' , 14.6)
    insert into products values ('tea' , 15.7)
    insert into products values ('sugar' , 16.8)
    insert into products values ('salt' , 17.9)
    insert into products values ('chocolate' , 18.1)
    insert into products values ('cake' , 19.2)

    insert into users values ('user', '$2a$10$P6aWpRZYESDlkl1Zw24QIeu4jJMYhvW.pCHK8r2y/XD3G9uw6.lni','Elizaveta','Terente','Tschurtschenthalerstrasse 7','+436704085535','veronika.viskey@yandex.ru')
    insert into user_role (user_name, roles) values ('user', 'USER')
    insert into users values ('admin', '$2a$10$P6aWpRZYESDlkl1Zw24QIeu4jJMYhvW.pCHK8r2y/XD3G9uw6.lni','admin_name','admin_surname','admin_adress','admin_phone_number','admin_email')
    insert into user_role (user_name, roles) values ('admin', 'ADMIN')